#!/usr/bin/python3
import aiosqlite
import asyncio
import random
import click
import time
import sys
import os

home_dir = os.environ["HOME"]

lvl = (
        0,                      # 0 - immediately
        60 * 20,                # 1 - 20 mins
        60 * 60,                # 2 - 1 hr
        60 * 60 * 9,            # 3 - 9 hrs
        60 * 60 * 24,           # 4 - next day
        60 * 60 * 24 * 2,       # 5 - 2 days
        60 * 60 * 24 * 6,       # 6 - 6 days
        60 * 60 * 24 * 14,      # 7 - 2 weeks
        60 * 60 * 24 * 30,      # 8 - 1 month
        60 * 60 * 24 * 30 * 2,  # 9 - 2 months
        60 * 60 * 24 * 30 * 6,  # 10 - 6 months
        60 * 60 * 24 * 30 * 12 * 1000,  # 11 - 1000 yrs
        )

async def get_new_id():
    last_id = 0
    async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
        await db.execute('create table if not exists flashcards (id int, front mediumtext, back mediumtext, lvl int, tags, timestamp int)')
        await db.commit()
        async with db.execute('select MAX(id) from flashcards') as cursor:
            async for row in cursor:
                last_id = row[0]
    if type(last_id) != int:
        async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
            await db.execute(f'insert into flashcards(id, front, back, lvl, tags, timestamp) values (-2, "meta", "enabled", 11, json("[]"), {time.time()})')
            await db.commit()
            await db.execute(f'insert into flashcards(id, front, back, lvl, tags, timestamp) values (-1, "meta", "disabled", 11, json("[]"), {time.time()})')
            await db.commit()
        return 0
    else:
        return last_id + 1

async def get_table():
    async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
        async with db.execute('select * from flashcards') as cursor:
            async for row in cursor:
                print(row)

# TODO: add support for all special symbols. Currently it gives syntax error if all special symbols are entered.
async def add_card():
    print('front: ')
    front = input()
    if front == 'q':
        return False
    print('back: ')
    back = input()
    print('---')
    card = {
            'id': await get_new_id(),
            'front': front, 'back': back,
            'lvl': 0,
            'timestamp': int(time.time())
            }
    async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
        await db.execute(
                f"""insert into flashcards(id, front, back, lvl, tags, timestamp) values ({card['id']}, '{card['front']}', '{card['back']}', {card['lvl']}, json('["{card['front']}"]'), {card['timestamp']})"""
                   )
        # select front,back from flashcards, json_each(tags) where json_each.value='second one';
        await db.commit()
    return True

async def get_active_cards():
    cards = []
    now = int(time.time())
    async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
        async with db.execute('select * from flashcards') as cursor:
            async for row in cursor:
                card = {
                        'id': row[0],
                        'front': row[1],
                        'back': row[2],
                        'lvl': row[3],
                        'tags': row[4],
                        'timestamp': row[5]
                        }
                if now - card['timestamp'] >= lvl[card['lvl']]:
                    cards.append(card)
    return cards

def erase_line():
    print("\033[A\033[2K\033[A")    # erase current line: [A cursor up, [2K erase whole line

async def memorize(cards):
    now = int(time.time())
    should_exit = False
    random.shuffle(cards)
    for card in cards:
        print(card["front"])
        front = True
        while True:
            user_input = click.getchar()
            erase_line()
            if user_input == 'f':
                if front:
                    print(card["back"])
                    front = False
                else:
                    print(card["front"])
                    front = True
            elif user_input == 'd':
                await delete_card(card)
                cards.remove(card)
                break
            elif user_input == 'y':
                while lvl[card["lvl"]] < now - card["timestamp"]:
                    card["lvl"] += 1
                break
            elif user_input == 'n':
                card["lvl"] = 0
                break
            else:
                should_exit = True
                break
        card["timestamp"] = now
        if should_exit:
            break
    await update_db(cards)
    if should_exit:
        exit()
    return cards

async def update_db(cards):
    async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
        for row in cards:
            await db.execute(
                    f'update flashcards set lvl = {row['lvl']} where id = "{row['id']}"')
            await db.commit()
            await db.execute(
                    f'update flashcards set timestamp = {row['timestamp']} where id = "{row['id']}"')
            await db.commit()
            await db.execute(
                    f"""update flashcards set tags = '{row["tags"]}' where id = '{row["id"]}'""")
            await db.commit()
            await db.execute(
                    f"""update flashcards set back = '{row["back"]}' where id = '{row["id"]}'""")
            await db.commit()

async def delete_card(card):
    async with aiosqlite.connect(f'{home_dir}/.cache/fls/flashcards.db') as db:
        await db.execute(
                f'delete from flashcards where id = "{card['id']}"')
        await db.commit()

async def add_tag(card):
    pass

async def del_tag(card):
    pass

async def list_tags(card):
    pass

async def disable_tag():
    pass

async def enable_tag():
    pass

async def list_all_tags():
    pass

async def list_by_tag():
    pass

async def main():
    if len(sys.argv) >= 2 and sys.argv[1] == 'a':
        while await add_card():
            pass
    #elif len(sys.argv) >= 2 and sys.argv[1] == 'l':
        #await get_table()  # for developers. The learner doesn't want to have this function available
    else:
        while True:
            cards = await get_active_cards()
            if not len(cards):
                break
            cards = await memorize(cards)

if __name__ == '__main__':
    asyncio.run(main())
